config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"
  get "search" => "searches#search"
  resources :users, only: [:show, :create, :index, :edit, :update]
  resources :devise, only:[:new ,:edit]
  resources :books, only: [:create, :index, :show, :destroy, :update, :edit] do
  resources :book_comments, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
  end
   resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
    get :followings, :followers
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction,length: { maximum: 50 } 
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  def get_profile_image(width,height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end       
  
  def follow(user_id)
  relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
  followings.include?(user)
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :is_matching_login_user, only: [:edit, :update]
    before_action :set_user, only: [:followings, :followers]
  def show
    @user = User.find(params[:id])
    Book.where(user_id: @user.id).all 
    @books = @user.books.all
    @set_relationship = current_user.relationships.new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    if @user.save
     redirect_to "/users/#{@user.id}"
    else
      render 'users/edit'
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def index
    @user = current_user
    @users = User.all
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id)
    flash[:notice] = "You have updated user successfully."
    else
      render 'users/edit'
    end
  end
  
  def destroy
    @user.delete(:user_id)
    @current_user = nil
    flash[:notice] = "Signed out successfully."
    redirect_to :root
  end
  
  def followings
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def is_matching_login_user
    user_id = params[:id].to_i
    unless user_id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
  
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<html>
  <head></head>
  <% if @user.errors.any? %>
         <%=  @user.errors.count %>errors prohibited this obj from being saved:
         <ul>
          <%  @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
          </ul>
           <% end %>
  
  <body>
    
    <div class ="containar">
      <div class ="row">
        <div class ="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <h1>Editing User</h1>
          <%= form_with model: @user do |f| %>
          <div class ="form_grpup">
            <%= f.label:Name %> <br>
            <%= f.text_field :name %> 
             <div class ="form_grpup">
               <div class="field">
               <%= f.label:Image %> <br>
               <%= f.file_field :profile_image %>
               </div>
             </div>
             <div class="form-group">
               <%= f.label:Introduction %> <br>
              <%= f.text_area :introduction %><br>
              <%= f.submit 'Update User', class:'btn btn-secondary'  %>
            </div>
        </div>
      </div>
    </div>
    <% end %>
  </body>

app/views/users/index.html.erb
<html>
  <head></head>
  <%= flash[:notice] %>
  <body>
      
    <main>
      <p id ="notice"></p>
      <div class= "container px-5 px-sm-0">
              <div class= "row">
      <div class ="col-md-3">
        <h1>User info</h1>
              <% if @user.profile_image? %>
             <%= image_tag @user.profile_image.url %>
             <% else %>
             <%= image_tag ("default-image.jpg") %>
          <% end %>
         
        <table class= "table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
            <tr>
                <th>
                    <h2>follower：
                        <%= link_to  @user.followings.count,followings_user_path(@user) %>
                        <% @user.followings.each do |u| %>
                        <% end %></2>
                        <h2>followers：
                        <%= link_to @user.followers.count,followers_user_path(@user) %>
                        <% @user.followings.each do |u| %>
                        <% end %></2>
                </th>
            </tr>
          </tbody>
        </table>
         <div class ="row">
             <% @user.id == current_user.id %>
           <%= link_to  edit_user_path(@user), class: "btn btn-outline-secondary btn-block" do %>
            <strong><i class="fas fa-user-cog "></i></strong>
             <% end %>      
        </div>
          <%= form_with model: Book.new do |f| %>
          <h2 class="mt-3">New book</h2>
        <h4>Title</h4>
          <%= f.text_field :title %>
        <h4>Option</h4>
         <%= f.text_area :body %>
          <%= f.submit 'Create Book', class:'btn btn-sm btn-success'  %>
        </div>
          <% end %>


    <div class ="col-md-8 offset-md-1">
        <%= render 'searchs/form' %>
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
         <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
          <th colspan="3"></th>
         </tr>
        </thead>
       <tbody>
         <% @users.each do |user| %>
          <tr>
           <td>
            <%= image_tag 'default-image.jpg', size: "75x75" %>
            </td>
            <td><%=  user.name %></td>
            <% if unless user == current_user %>
            <td>
                <% if current_user.following?(user) %>
                <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
                <% else %>
                <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                <% end %>
            </td>
            <% end %>
            <% end %>
            <td><%= link_to 'Show', user_path(user.id) %></td>
          </tr>
          <% end %>
       </tbody>
      </table>
    </body>   
 </html>

app/views/users/show.html.erb
<html>
  <head></head>
  <body>
    <main>
      <%= flash[:notice] %>
       <p id ="notice"></p>
      <div class= "container px-5 px-sm-0">
              <div class= "row">
      <div class ="col-md-3">
        <h1>User info</h1>
         <% if @user.profile_image? %>
             <%= image_tag @user.profile_image.url %>
             <% else %>
             <%= image_tag ("default-image.jpg") %>
          <% end %>
        
        <table class= "table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
            <tr>
             <tr>
                <th>
                    <h2>follower：
                        <%= link_to  @user.followings.count,followings_user_path(@user) %>
                        <% @user.followings.each do |u| %>
                        <% end %></2>
                        <h2>followers：
                        <%= link_to @user.followers.count,followers_user_path(@user) %>
                        <% @user.followings.each do |u| %>
                        <% end %></2>
                </th>
                
               </div>
              </td>
            </tr>
            <tr>
                <div class='row'>
                 <% if current_user != @user %>
                   <td><%= render "relationships/btn", user: @user %></td>
                <% end %>
            </tr>
          </tbody>
        </table>
         <div class ="row">
            <% @user.id == current_user.id %>
           <%= link_to  edit_user_path(@user), class: "btn btn-outline-secondary btn-block" do %>
            <strong><i class="fas fa-user-cog "></i></strong>
             <% end %>      
        </div>
          <%= form_with model: Book.new do |f| %>
          <h2 class="mt-3">New book</h2>
        <h4>Title</h4>
          <%= f.text_field :title %>
        <h4>Option</h4>
          <%= f.text_area :body %>
          <%= f.submit 'Create Book', class:'btn btn-sm btn-success'  %>
           </div>
          <% end %>
    <div class ="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
         <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
         </tr>
        </thead>
        <tbody>
          <tr>         
         <% @books.each do |book| %>
          <td><%= link_to user_path(@user.id) do %>
             <% if @user.profile_image? %>
             <%= image_tag @user.profile_image.url %>
             <% else %>
             <%= image_tag ("default-image.jpg") %>
         <% end %><br>
         </td>
           <span><td><%= link_to  book.title , book_path(book) %></td></span>
           <td><%= book.body %></td>
            <% end %>
          </tr>
          <% end %>
       </tbody>
    </table>
    <tr>
      <th></th>
      <th></th>
      <% @books.each do |book| %>
      <th></th>
      <th colspan="3"></th>
    </tr>
    <% end %>
    </div>
   </div>
  </main>
  </body>
</html>

app/views/users/stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>