config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"
  get "search" => "searches#search"
  resources :users, only: [:show, :create, :index, :edit, :update]
  resources :devise, only:[:new ,:edit]
  resources :books, only: [:create, :index, :show, :destroy, :update, :edit] do
  resources :book_comments, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
  end
   resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
    get :followings, :followers
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
 def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
     redirect_to "/books/#{@book.id}"
     flash[:notice] = "You have created book successfully."
    else
      @books = Book.all
      @user = current_user
      render :index
    end
 end
 
  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
    @users = User.all
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @newbook = Book.new
    @book_comment = BookComment.new
  end
  
  def edit
    @book = Book.find (params[:id])
  end
  
 def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    @book.user_id = current_user.id
    redirect_to "/books/#{@book.id}"
    flash[:notice] = "You have updated book successfully."
    else
      render 'books/edit'
    end
 end     
   
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  
  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :book_name, :caption, :user_id)
  end
  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
end

def is_matching_login_user
    book_id = Book.find(params[:id])
    unless book_id.user_id == current_user.id
      redirect_to books_path
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
<table><% books.book_comments.each do |book_comment| %>

   <tr>
    <td>
    <%= attachment_image_tag book_comment.user, :profile_image, format: 'jpeg',size: "50x50",fallback: "no_image.jpg" %><br>
    <%=link_to user_path(books.user.id) do %><%= book_comment.user.name %><% end %></td>


    <td><%= book_comment.comment %></td>
  <% if book_comment.user == current_user %>
    <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete,remote: true,class:"btn btn-danger" %></td>

  <% end %>
  </tr>
  <% end %>

 </table>

 <div class="form-group">
  <label for="newcomment">Comment</label>



 <%= form_with(model:[books, book_comment], local: true) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに",class:"form-control" %>
  <%= f.submit "送信する" %>
 <% end %>
 </div>

app/views/books/edit.html.erb
<html class="class="fontawesome-i2svg-active fontawesome-i2svg-complete"">
  <head></head>
  <body>
    <%= flash[:notice] %>
    <% if @book.errors.any? %>
         <%= @book.errors.count %>errors prohibited this obj from being saved:
         <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
          </ul>
           <% end %>
    <main>
    <p id="notice"></p>
    <div class ="containar">
      <div class ="row">
        <div class ="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <h1>Editing Book</h1>
          <%= form_with model: @book do |f| %>
          
            <div class ="form_grpup">
              <%= f.label:Title %> <br>
            <%= f.text_field :title %> 
            </div>
             
            <div class="form-group">
            <%= f.label :Opinion %><br>
            <%= f.text_area :body %>
            </div>
            <div class="form-group">
              <%= f.submit 'Update Book' , class:'btn btn-sm btn-success'  %>
            </div>

            <div class="form-group">
            <%= link_to "Show","/books/#{@book.id}" %> | <%= link_to "Back", books_path %>
            </div>
        </div>
      </div>
  </div>
    <% end %>
    </main>
  </body>

app/views/books/index.html.erb
<html>
  <head></head>
  <body>
    <% if @book.errors.any? %>
         <%= @book.errors.count %>errors prohibited this obj from being saved:
         <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
          </ul>
           <% end %>
    <main>
      <p id ="notice"></p>
      <div class= "container px-5 px-sm-0">
              <div class= "row">
      <div class ="col-md-3">
        
        <h1>User info</h1>
         <% if @user.profile_image? %>
             <%= image_tag @user.profile_image.url %>
             <% else %>
             <%= image_tag ("default-image.jpg") %>
          <% end %>
        
        <table class= "table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
            <tr>
                <th>
                    <h2>follower：
                        <%= link_to  @user.followings.count,followings_user_path(@user) %>
                        <% @user.followings.each do |u| %>
                        <% end %></2>
                        <h2>followers：
                        <%= link_to @user.followers.count,followers_user_path(@user) %>
                        <% @user.followings.each do |u| %>
                        <% end %></2>
                </th>
            </tr>
          </tbody>
        </table>
         <div class ="row">
            <% @user.id == current_user.id %>
           <%= link_to  edit_user_path(@user), class: "btn btn-outline-secondary btn-block" do %>
            <strong><i class="fas fa-user-cog "></i></strong>
             <% end %>     
        </div>
        
          <%= form_with model: Book.new do |f| %>
          <h2 class="mt-3">New book</h2>
        <h4>Title</h4>
          <%= f.text_field :title %>
        <h4>Option</h4>
         <%= f.text_area :body %>
          <%= f.submit 'Create Book', class:'btn btn-sm btn-success'  %>
           </div>
          <% end %>


    <div class ="col-md-8 offset-md-1">
     <%= render 'searchs/form' %>
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
         <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
         </tr>
        </thead>
       <tbody>
         <% @books.each do |book| %>
          <tr>
           <td><%= link_to user_path(book.user.id) do %>
            <%= image_tag 'default-image.jpg', size: "75x75" %>
            <% end %>
           </td>
            <span><td><%= link_to  book.title, "/books/#{book.id}" %></td></span>
            <td><%= book.body %></td>
            <td><% if book.favorited_by?(current_user) %>
            <p>
            <%= link_to book_favorites_path(book), method: :delete do %>
            ♥<%= book.favorites.count %> 
            <% end %>
            </p>
            <% else %>
            <p>
            <%= link_to book_favorites_path(book), method: :post do %>
             ♡<%= book.favorites.count %> 
             <% end %>
            </p><% end %>
            </td>
            <td> コメント件数：<%= book.book_comments.count %><br></td>
          </tr>
          <% end %>
       </tbody>
    </table>

       
 </tbody>
    </tr>
    </div>
  </div>  

app/views/books/new.html.erb
<html>
  <head></head>
  <body>
    <main>
       <p id ="notice"></p>
      <div class= "container px-5 px-sm-0">
              <div class= "row">
      <div class ="col-md-3">
        <h1>User info</h1>
        <% if @user.profile_image.attached? %>
           <%= image_tag book.image, size: "100x100" %>
          <% else %>
          <%= image_tag 'no_image', size: "100x100" %>
         <% end %>
        <table class= "table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th></th>
            </tr>
          </tbody>
        </table>
         <div class ="row">
           <a class="btn btn-outline-secondary btn-block edhit_user_path"  edhit_path >
            <svg class="svg-inline--fa fa-user-cog fa-w-20" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="user-cog" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512" data-fa-i2svg=""><path fill="currentColor" d="M610.5 373.3c2.6-14.1 2.6-28.5 0-42.6l25.8-14.9c3-1.7 4.3-5.2 3.3-8.5-6.7-21.6-18.2-41.2-33.2-57.4-2.3-2.5-6-3.1-9-1.4l-25.8 14.9c-10.9-9.3-23.4-16.5-36.9-21.3v-29.8c0-3.4-2.4-6.4-5.7-7.1-22.3-5-45-4.8-66.2 0-3.3.7-5.7 3.7-5.7 7.1v29.8c-13.5 4.8-26 12-36.9 21.3l-25.8-14.9c-2.9-1.7-6.7-1.1-9 1.4-15 16.2-26.5 35.8-33.2 57.4-1 3.3.4 6.8 3.3 8.5l25.8 14.9c-2.6 14.1-2.6 28.5 0 42.6l-25.8 14.9c-3 1.7-4.3 5.2-3.3 8.5 6.7 21.6 18.2 41.1 33.2 57.4 2.3 2.5 6 3.1 9 1.4l25.8-14.9c10.9 9.3 23.4 16.5 36.9 21.3v29.8c0 3.4 2.4 6.4 5.7 7.1 22.3 5 45 4.8 66.2 0 3.3-.7 5.7-3.7 5.7-7.1v-29.8c13.5-4.8 26-12 36.9-21.3l25.8 14.9c2.9 1.7 6.7 1.1 9-1.4 15-16.2 26.5-35.8 33.2-57.4 1-3.3-.4-6.8-3.3-8.5l-25.8-14.9zM496 400.5c-26.8 0-48.5-21.8-48.5-48.5s21.8-48.5 48.5-48.5 48.5 21.8 48.5 48.5-21.7 48.5-48.5 48.5zM224 256c70.7 0 128-57.3 128-128S294.7 0 224 0 96 57.3 96 128s57.3 128 128 128zm201.2 226.5c-2.3-1.2-4.6-2.6-6.8-3.9l-7.9 4.6c-6 3.4-12.8 5.3-19.6 5.3-10.9 0-21.4-4.6-28.9-12.6-18.3-19.8-32.3-43.9-40.2-69.6-5.5-17.7 1.9-36.4 17.9-45.7l7.9-4.6c-.1-2.6-.1-5.2 0-7.8l-7.9-4.6c-16-9.2-23.4-28-17.9-45.7.9-2.9 2.2-5.8 3.2-8.7-3.8-.3-7.5-1.2-11.4-1.2h-16.7c-22.2 10.2-46.9 16-72.9 16s-50.6-5.8-72.9-16h-16.7C60.2 288 0 348.2 0 422.4V464c0 26.5 21.5 48 48 48h352c10.1 0 19.5-3.2 27.2-8.5-1.2-3.8-2-7.7-2-11.8v-9.2z"></path></svg>
           </a>
        </div>
          </ul>
           <% end %>
          <%= form_with model: Book.new do |f| %>
          <h2 class="mt-3">New book</h2>
        <h4>Title</h4>
          <%= f.text_field :title %>
        <h4>Option</h4>
          <%= f.text_area :body %>
          <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
          
        </div>
    <% end %>
    <div class ="col-md-8 offset-md-1">
      <h2>Users</h2>

      <table class="table table-hover table-inverse">
        <thead>
         <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
         </tr>
        </thead>
       <tbody>
        <tr>
         <td><% if @user.profile_image? %>
             <%= image_tag @user.profile_image.url %>
             <% else %>
             <%= image_tag ("default-image.jpg") %>
           <% end %></td>
         <td><% @users.each do |user| %>
      　    <%= link_to user.name, user %></td>　
   　　　　 <% end %>
   　　　 　<td><%= link_to 'Show',@book %></td>
　　　　　</td>
         </tr>      
      </tbody>
    </table>
    <tr>
      <th></th>
      <th></th>
            <% @books.each do |book| %>

      <th></th>
      <th colspan="3"></th>
    </tr>
    <% end %>
    </div>
   </div>
  </main>
  </body>
  <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/books/show.html.erb
<html>
  <head></head>
  <body>
    <%= flash[:notice] %>
    <main>
       <p id ="notice"></p>
      <div class= "container px-5 px-sm-0">
              <div class= "row">
      <div class ="col-md-3">
        <h1>User info</h1>
        <% if @user.profile_image? %>
             <%= image_tag @user.profile_image.url %>
             <% else %>
             <%= image_tag ("default-image.jpg") %>
          <% end %>
        <table class= "table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
             <tr>
                <th>
                    <h2>follower：
                        <%= link_to  @user.followings.count,followings_user_path(@user) %>
                        <% @user.followings.each do |u| %>
                        <% end %></2>
                        <h2>followers：
                        <%= link_to @user.followers.count,followers_user_path(@user) %>
                        <% @user.followings.each do |u| %>
                        <% end %></2>
                </th>
            </tr>
          </tbody>
        </table>
         <div class ="row">
            <% @user.id == current_user.id %>
           <%= link_to  edit_user_path(@user), class: "btn btn-outline-secondary btn-block" do %>
            <strong><i class="fas fa-user-cog "></i></strong>
             <% end %>      
        </div>
          <%= form_with model: Book.new do |f| %>
           <h2 class="mt-3">New book</h2>
        <h4>Title</h4>
          <%= f.text_field :title %>
        <h4>Option</h4><br>
         <%= f.text_area :body %>
         <%= f.submit 'Create Book', class:'btn btn-sm btn-success'  %>
        </div>
          <% end %>

    <div class ="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class ="table">
        <tbody>
         <tr>
          
          <td><%= link_to user_path(@user.id) do %>
             <% if @user.profile_image? %>
             <%= image_tag @user.profile_image.url %>
             <% else %>
             <%= image_tag ("default-image.jpg") %>
         <% end %><br>
           <%= @user.name %>
           <% end %>
            </td>            
            <td><%= link_to  @book.title ,"/books/#{@book.id}"%></td>
            <td><%= @book.body %></td>
             <td>
               <div>
                   コメント件数：<%= @book.book_comments.count %><br>
                </div>   
           </td>
            <% if @user.id == current_user.id %>
           <td><%= link_to 'Edit', edit_book_path(@book),class:"btn-sm btn-success" %></td>
           <td><%= link_to 'Destroy', @book, method: :delete,class:"btn btn-sm btn-danger", data: { confirm: '本当に消しますか？' } %></td>
           <% end %>
           <td>
               <% @book.book_comments.each do |book_comment| %>
                    <p><%= image_tag book_comment.user.get_profile_image(100,100) %></p>
                       <%= book_comment.user.name %>
                       <%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.comment %>
                       <% if book_comment.user == current_user %>
                       <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete ,class:"btn btn-sm btn-danger" %>
                       <% end %>
                       <% end %>
                </div>
              <div>
                <%= form_with model: [@book, @book_comment] do |f| %>
                <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
                <%= f.submit "送信する" %>
                <% end %>
             </div>   
           </td>
           
        </tr>
            
           
            
        </div>
        
        </tbody>
        
      </table>
      
    </main>
    
   </body>
</html>