config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"
  get "search" => "searches#search"
  resources :users, only: [:show, :create, :index, :edit, :update]
  resources :devise, only:[:new ,:edit]
  resources :books, only: [:create, :index, :show, :destroy, :update, :edit] do
  resources :book_comments, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
  end
   resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
    get :followings, :followers
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
     @users = User.looks(params[:search],params[:word])
     render "/searchs/search_result"
    else
     @books = Book.looks(params[:search], params[:word])
     render "/searchs/search_result"
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/searchs/_form.html.erb
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/searchs/search_result.html.erb
<table class="table table-hover table-inverse">
  <% if @range == "User" %>
  <%= render 'searchs/form' %>
  <div class ="col-md-8 offset-md-1">
      <h2>Users search for "<%= @content %>"</h2>
      <table class="table table-hover table-inverse">
        <thead>
         <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
          <th colspan="3"></th>
         </tr>
        </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
          <%= image_tag 'default-image.jpg', size: "75x75" %>
          </td>
          <td><%= user.name %></td>
          <td><%= link_to 'Show', user_path(user.id) %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <tbody>
      <% @books.each do |book| %>
        <div class ="col-md-8 offset-md-1">
        <%= render 'searchs/form' %>
        <h2>Books search for "<%= @content %>"</h2>
        <thead>
         <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
         </tr>
        </thead>
        <tr>
        <td><%= image_tag 'default-image.jpg', size: "75x75" %></td>
          <td><%= link_to  book.title, "/books/#{book.id}" %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>