config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"
  get "search" => "searches#search"
  resources :users, only: [:show, :create, :index, :edit, :update]
  resources :devise, only:[:new ,:edit]
  resources :books, only: [:create, :index, :show, :destroy, :update, :edit] do
  resources :book_comments, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
  end
   resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
    get :followings, :followers
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction,length: { maximum: 50 } 
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  def get_profile_image(width,height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end       
  
  def follow(user_id)
  relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
  followings.include?(user)
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
 def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
     redirect_to "/books/#{@book.id}"
     flash[:notice] = "You have created book successfully."
    else
      @books = Book.all
      @user = current_user
      render :index
    end
 end
 
  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
    @users = User.all
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @newbook = Book.new
    @book_comment = BookComment.new
  end
  
  def edit
    @book = Book.find (params[:id])
  end
  
 def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    @book.user_id = current_user.id
    redirect_to "/books/#{@book.id}"
    flash[:notice] = "You have updated book successfully."
    else
      render 'books/edit'
    end
 end     
   
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  
  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :book_name, :caption, :user_id)
  end
  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
end

def is_matching_login_user
    book_id = Book.find(params[:id])
    unless book_id.user_id == current_user.id
      redirect_to books_path
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
     @users = User.looks(params[:search],params[:word])
     render "/searchs/search_result"
    else
     @books = Book.looks(params[:search], params[:word])
     render "/searchs/search_result"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :is_matching_login_user, only: [:edit, :update]
    before_action :set_user, only: [:followings, :followers]
  def show
    @user = User.find(params[:id])
    Book.where(user_id: @user.id).all 
    @books = @user.books.all
    @set_relationship = current_user.relationships.new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    if @user.save
     redirect_to "/users/#{@user.id}"
    else
      render 'users/edit'
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def index
    @user = current_user
    @users = User.all
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id)
    flash[:notice] = "You have updated user successfully."
    else
      render 'users/edit'
    end
  end
  
  def destroy
    @user.delete(:user_id)
    @current_user = nil
    flash[:notice] = "Signed out successfully."
    redirect_to :root
  end
  
  def followings
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def is_matching_login_user
    user_id = params[:id].to_i
    unless user_id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
  
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="csrf-param" content="authenticity_token">
    <html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
    <%= csrf_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
 <body class="d-flex flex-column vh-100">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
       <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li class="nav-item">
          <li>
             <%= link_to  user_path(current_user.id) ,class: "nav-link text-light" do %>
             <strong><i class="fas fa-home"></i>Home</strong>
             <% end %>
          </li>
          <li>
             <%= link_to  users_path ,class: "nav-link text-light" do %>
             <strong><i class="fas fa-users"></i>Users</strong>
             <% end %>
          </li>
          <li>
             <%= link_to  books_path ,class: "nav-link text-light" do %>
             <strong><i class="fas fa-book-open"></i>Books</strong>
             <% end %>
          </li>
          <li>
             <%= link_to destroy_user_session_path, method: :delete,class: "nav-link text-light" do %>
             <strong><i class="fas fa-sign-out-alt"></i>Log out</strong>
            <% end %>
          <% else %>
          <li>
            <%= link_to  root_path ,class: "nav-link text-light" do %>
             <strong><i class="fas fa-home"></i>Home</strong>
             <% end %>
          </li>
          <li>
            <li>
            <%= link_to  about_path ,class: "nav-link text-light" do %>
             <strong><i class="fas fa-link"></i>About</strong>
             <% end %>
          </li>
          <li>
            <%= link_to  new_user_registration_path ,class: "nav-link text-light" do %>
             <strong><i class="fas fa-user-plus"></i>Sign up</strong>
             <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path, class: "nav-link text-light" do %>
            <strong><i class="fas fa-sign-in-alt"></i>Log in</strong>
            <% end %>
          </li>
          <% end %>
        </ul>
        </ul>
        </ul>
        </ul>
      </div>
    </div>
  </nav>
</header>

<main class="mb-auto">
    <%= yield %>
</main>
</body>
<footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
</html>